### ISSUE TITLE
Print Button on the Daily Rollup Does Not Work

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#376]
The white "Print" button on the Daily Rollup  does not work.  A new browser tab is displayed (as designed) but a HTTP 500 Internal Server Error is displayed.

This bug was noticed by users immediately after the release of version 2.0.6.

Reference item 132

**Comment by VassilIordanov** [comment]
I could reproduce this, with the following error:

```ERROR [2018-01-09 12:12:39,981] freemarker.runtime: Error executing FreeMarker template
! freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
! ==> report.loadTask  [in template "emails/rollup.ftl" at line 156, column 26]
! 
! ----
! Tip: It's the step after the last dot that caused this error, not those before it.
! ----
! Tip: If the failing expression is known to be legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
! ----
! 
! ----
! FTL stack trace ("~" means nesting-related):
! - Failed at: #assign tasks = report.loadTask()  [in template "emails/rollup.ftl" in macro "renderReport" at line 156, column 9]
! - Reached through: @renderReport report  [in template "emails/rollup.ftl" at line 105, column 49]
! ----
! at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:131)
! at freemarker.core.UnexpectedTypeException.newDesciptionBuilder(UnexpectedTypeException.java:77)
! at freemarker.core.UnexpectedTypeException.<init>(UnexpectedTypeException.java:40)
! at freemarker.core.NonMethodException.<init>(NonMethodException.java:46)
! at freemarker.core.MethodCall._eval(MethodCall.java:84)
! at freemarker.core.Expression.eval(Expression.java:78)
! at freemarker.core.Assignment.accept(Assignment.java:131)
! at freemarker.core.Environment.visit(Environment.java:324)
! at freemarker.core.MixedContent.accept(MixedContent.java:54)
! at freemarker.core.Environment.visit(Environment.java:324)
! at freemarker.core.Macro$Context.runMacro(Macro.java:184)
! at freemarker.core.Environment.invoke(Environment.java:701)
! at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
! at freemarker.core.Environment.visit(Environment.java:324)
! at freemarker.core.MixedContent.accept(MixedContent.java:54)
! at freemarker.core.Environment.visitByHiddingParent(Environment.java:345)
! at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:48)
! at freemarker.core.Environment.visitByHiddingParent(Environment.java:345)
! at freemarker.core.IteratorBlock$IterationContext.executeNestedBlockInner(IteratorBlock.java:268)
! at freemarker.core.IteratorBlock$IterationContext.executeNestedBlock(IteratorBlock.java:220)
! at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:194)
! at freemarker.core.Environment.visitIteratorBlock(Environment.java:572)
! at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:78)
! at freemarker.core.IteratorBlock.accept(IteratorBlock.java:64)
! at freemarker.core.Environment.visit(Environment.java:324)
! at freemarker.core.MixedContent.accept(MixedContent.java:54)
! at freemarker.core.Environment.visitByHiddingParent(Environment.java:345)
! at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:48)
! at freemarker.core.Environment.visitByHiddingParent(Environment.java:345)
! at freemarker.core.IteratorBlock$IterationContext.executeNestedBlockInner(IteratorBlock.java:268)
! at freemarker.core.IteratorBlock$IterationContext.executeNestedBlock(IteratorBlock.java:220)
! at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:194)
! at freemarker.core.Environment.visitIteratorBlock(Environment.java:572)
! at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:78)
! at freemarker.core.IteratorBlock.accept(IteratorBlock.java:64)
! at freemarker.core.Environment.visit(Environment.java:324)
! at freemarker.core.MixedContent.accept(MixedContent.java:54)
! at freemarker.core.Environment.visitByHiddingParent(Environment.java:345)
! at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:48)
! at freemarker.core.Environment.visitByHiddingParent(Environment.java:345)
! at freemarker.core.IteratorBlock$IterationContext.executeNestedBlockInner(IteratorBlock.java:268)
! at freemarker.core.IteratorBlock$IterationContext.executeNestedBlock(IteratorBlock.java:220)
! at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:194)
! at freemarker.core.Environment.visitIteratorBlock(Environment.java:572)
! at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:78)
! at freemarker.core.IteratorBlock.accept(IteratorBlock.java:64)
! at freemarker.core.Environment.visit(Environment.java:324)
! at freemarker.core.MixedContent.accept(MixedContent.java:54)
! at freemarker.core.Environment.visit(Environment.java:324)
! at freemarker.core.Environment.process(Environment.java:302)
! at freemarker.template.Template.process(Template.java:325)
! at mil.dds.anet.resources.ReportResource.showRollupEmail(ReportResource.java:760)
! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
! at java.lang.reflect.Method.invoke(Method.java:498)
....
```
